name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
                cd /var/www/html/my-project-cicd

                git pull origin main

                composer install --no-dev --optimize-autoloader --ignore-platform-req=php

                php artisan config:cache
                php artisan route:cache
                php artisan view:cache
                php artisan optimize:clear